"""
backend/services/generator.py

Calls the OpenRouter API to generate answers grounded strictly
in the retrieved source chunks.

Model: GENERATION_MODEL in .env (default: an OpenRouter free-tier model,
id ending in ":free" -- $0 per token). See .env for how to swap it.

OpenRouter uses an OpenAI-compatible API, so we use the openai
Python package pointed at https://openrouter.ai/api/v1.

Add to your .env file:
    OPENROUTER_API_KEY=sk-or-your-key-here
"""

import os
import sys
from pathlib import Path
from typing import AsyncGenerator

from openai import APIStatusError, OpenAI

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

# AFTER (Groq Setup) 🚀
# Updated for currently supported Groq models ⚡
GENERATION_MODEL = os.getenv("GENERATION_MODEL", "llama-3.3-70b-versatile")
MAX_TOKENS       = 1024
GROQ_URL         = "https://api.groq.com/openai/v1"

_FALLBACK_MODELS = list(dict.fromkeys([
    GENERATION_MODEL,
    "llama-3.3-70b-versatile",
    "openai/gpt-oss-120b",
    "openai/gpt-oss-20b",
]))

def _create_with_fallback(client: OpenAI, require_content: bool = True, **kwargs):
    """
    Try each free model in _FALLBACK_MODELS until one gives a usable
    response. Two ways a free model "fails" here:
      - APIStatusError (429/503/etc) -- rate-limited or temporarily down.
      - Empty message.content -- some free "reasoning" models spend their
        whole token budget on internal reasoning and never emit visible
        content, especially with the guardrail's tight max_tokens. Not
        something a caller can use, so treat it the same as an error and
        move to the next model. (Doesn't apply to streaming responses,
        which have no single .content to check up front.)
    """
    last_err = None
    for model in _FALLBACK_MODELS:
        # ✅ FIX #5: Added transparent log tracking to monitor hidden generation failures or rate limits
        print(f"[Generator] Attempting text generation with model: {model}")
        try:
            resp = client.chat.completions.create(model=model, **kwargs)
        except APIStatusError as e:
            print(f"[Generator] Warning: Model {model} failed with APIStatusError: {e}")
            last_err = e
            continue
        if require_content and not (resp.choices and resp.choices[0].message.content):
            print(f"[Generator] Warning: Model {model} returned an empty content body.")
            last_err = RuntimeError(f"{model} returned empty content")
            continue
        
        print(f"[Generator] Success! Text stream/payload generated by: {model}")
        return resp
    raise last_err


# AFTER (Groq Key Check) 🔑
def _get_client() -> OpenAI:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise EnvironmentError(
            "GROQ_API_KEY is not set. "
            "Add it to your .env file: GROQ_API_KEY=gsk_..."
        )
    return OpenAI(
        base_url = GROQ_URL,
        api_key  = api_key,
    )

def _build_context(chunks: list[dict]) -> str:
    """Format retrieved chunks into a numbered source block for the prompt."""
    lines = []
    for i, chunk in enumerate(chunks, 1):
        meta   = chunk.get("metadata", {})
        source = meta.get("source", "")
        book   = meta.get("book", "Unknown")

        if source == "hadith":
            hadith_num = meta.get("hadith_number") or ""
            grade      = meta.get("grade") or ""
            ref = f"{book}, Hadith #{hadith_num} (Grade: {grade})"
        else:
            surah = meta.get("surah") or ""
            ar    = meta.get("ayah_range") or []
            if ar and len(ar) == 2 and ar[0] != ar[1]:
                ayah = f"{ar[0]}-{ar[1]}"
            else:
                ayah = str(ar[0]) if ar else ""
            ref = f"{book}, Surah {surah}:{ayah}"

        lines.append(f"[Source {i}] {ref}\n{chunk['text']}")

    return "\n\n".join(lines)


def _system_prompt(language: str) -> str:
    lang_instruction = {
        "urdu":    "Answer in Urdu only.",
        "english": "Answer in English only.",
        "both":    "Answer in the same language the question was asked in. If the question mixes languages, prefer Urdu.",
    }.get(language, "Answer in the same language the question was asked in.")

    return f"""You are a high-precision Islamic knowledge assistant. Your answers are based ONLY on the source texts provided to you.

Rules you must follow without exception:
1. {lang_instruction}
2. Use ONLY the provided sources. Do not add any knowledge, historical facts, or assertions from outside the sources.
3. Cite every single claim with [Source N] referring to the numbered sources provided.
4. Critically evaluate the relevance of each source chunk. If a source passage is irrelevant, off-topic, or does not directly answer the user's question, you MUST completely IGNORE it. Do not mention or explain irrelevant sources in your final answer.
5. Strict Grounding Boundaries: Do not extrapolate, generalize, or smooth out conclusions. Frame significance using the exact phrasing of the text (e.g., if a source states 'prayer holds a noble status in worship', do NOT rewrite it as 'prayer is central to a Muslim's life' unless the words 'life' or 'centrality' are explicitly present in the text).
6. Tone Constraint: Maintain a highly factual, objective, and academic tone. Avoid adding generic, conversational, or conversational wrappers in your introduction or conclusion. State exactly what the provided texts say—no more, no less.
7. If the provided sources do not contain enough information to answer, say clearly:
   "The provided Islamic texts do not contain sufficient information on this topic."
   Do NOT guess, hypothesize, or fill gaps from general knowledge.
8. When quoting hadith, include the book name, hadith number, and grade.
9. When referencing tafsir, include the book name, surah number, and ayah number.
10. Be respectful and scholarly."""


def _user_prompt(question: str, context: str) -> str:
    return f"""Question: {question}

Retrieved Sources:
{context}

Please answer the question based strictly on the sources above."""


# ── synchronous generation ───────────────────────────────────────────────────

def generate_answer(
    question: str,
    chunks: list[dict],
    language: str = "both",
) -> str:
    """Generate a full answer string from retrieved chunks."""
    client  = _get_client()
    context = _build_context(chunks)

    response = _create_with_fallback(
        client,
        max_tokens = MAX_TOKENS,
        messages   = [
            {"role": "system", "content": _system_prompt(language)},
            {"role": "user",   "content": _user_prompt(question, context)},
        ],
    )
    return response.choices[0].message.content


# ── async streaming generation ───────────────────────────────────────────────

async def stream_answer(
    question: str,
    chunks: list[dict],
    language: str = "both",
) -> AsyncGenerator[str, None]:
    """
    Async generator that yields text tokens as they arrive.
    Used by the POST /query/stream endpoint.
    """
    client  = _get_client()
    context = _build_context(chunks)

    stream = _create_with_fallback(
        client,
        require_content = False,  # a stream has no single .content to check up front
        max_tokens = MAX_TOKENS,
        stream     = True,
        messages   = [
            {"role": "system", "content": _system_prompt(language)},
            {"role": "user",   "content": _user_prompt(question, context)},
        ],
    )
    for chunk in stream:
        delta = chunk.choices[0].delta
        if delta and delta.content:
            yield delta.content