"""
backend/services/guardrail.py

Post-generation groundedness check via Groq.

Model: GUARDRAIL_MODEL in .env -- kept as a separate setting from
GENERATION_MODEL so you can point the fact-check call at a smaller/faster
model than the main answer model if you want. 

Returns (passed: bool, reason: str).
  passed=True  → answer is grounded, safe to return to user
  passed=False → answer contains claims outside the sources
"""

import os
from openai import APIStatusError, OpenAI

# ✅ FIX #1: Default to a lightning-fast, non-reasoning Groq model
GUARDRAIL_MODEL = os.getenv("GUARDRAIL_MODEL", "llama-3.1-8b-instant") 
GROQ_URL = "https://api.groq.com/openai/v1"

# ✅ FIX #1: Refreshed fallback list to optimize execution speed
_FALLBACK_MODELS = list(dict.fromkeys([
    GUARDRAIL_MODEL,
    "llama-3.1-8b-instant",     # Primary fast, non-reasoning fallback
    "llama-3.3-70b-versatile",  # High-capacity model used only as a last resort
]))


# AFTER (Groq Key Check) 🔑
def _get_client() -> OpenAI:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise EnvironmentError("GROQ_API_KEY is not set in your .env file.")
    return OpenAI(base_url=GROQ_URL, api_key=api_key)

def _create_with_fallback(client: OpenAI, **kwargs):
    """
    Try each free model in _FALLBACK_MODELS. 
    """
    last_err = None
    for model in _FALLBACK_MODELS:
        # ✅ FIX #5: Added transparent log tracking to monitor hidden fallback triggers
        print(f"[Guardrail Check] Attempting model execution with: {model}")
        try:
            resp = client.chat.completions.create(model=model, **kwargs)
        except APIStatusError as e:
            print(f"[Guardrail Check] Warning: Model {model} failed with APIStatusError.")
            last_err = e
            continue
        if not (resp.choices and resp.choices[0].message.content):
            print(f"[Guardrail Check] Warning: Model {model} returned an empty content body.")
            last_err = RuntimeError(f"{model} returned empty content")
            continue
        
        print(f"[Guardrail Check] Success! Final output generated by: {model}")
        return resp
    raise last_err


def check_groundedness(
    answer: str,
    chunks: list[dict],
) -> tuple[bool, str]:
    """
    Returns (passed, reason).
    passed=True  → every claim in answer traces back to source chunks.
    passed=False → answer contains unsupported claims.
    """
    source_texts = "\n\n".join(
            f"""[Source {i+1}]

            Text:
            {c['text']}

            Metadata:
            Book: {c.get('metadata', {}).get('book', '')}
            Hadith Number: {c.get('metadata', {}).get('hadith_number', '')}
            Grade: {c.get('metadata', {}).get('grade', '')}
            """
            for i, c in enumerate(chunks)
       )

    prompt = f"""You are a fact-checker for an Islamic Q&A system.

Given the ANSWER below and the SOURCE TEXTS it was based on, determine
whether the ANSWER is a reasonable, faithful summary of the SOURCE TEXTS.

Minor paraphrasing, summarizing, or drawing an obvious conclusion that
follows directly from the source content is ACCEPTABLE and should PASS.

Only mark FAIL if the answer:
- States a fact, number, book name, hadith number, or grade that is not present
  in either the source text OR the provided metadata, or
- Contradicts something the source texts say, or
- Fabricates a citation to a source that doesn't support that claim.

Respond with exactly one of:
  PASS
  FAIL: <brief reason>

SOURCE TEXTS:
{source_texts}

ANSWER TO CHECK:
{answer}

Your verdict (PASS or FAIL: reason):"""
    client = _get_client()
    resp   = _create_with_fallback(
        client,
        # ✅ FIX #1: Dropped max_tokens from 400 to 60 since fast models do not waste tokens on internal reasoning loops
        max_tokens = 60,
        messages   = [{"role": "user", "content": prompt}],
    )

    verdict = resp.choices[0].message.content.strip()
    upper   = verdict.upper()
    
    # Keeps backward compatibility if an edge-case model prints thinking steps first
    passed  = upper.rfind("PASS") > upper.rfind("FAIL")
    reason  = verdict if not passed else "Grounded"
    return passed, reason


FALLBACK_MESSAGE = (
    "The system was unable to generate a fully grounded answer from the "
    "available Islamic source texts. Please rephrase your question or ask "
    "about a topic covered in the hadith or tafsir collections."
)